export const GET_MOVIES_POPULAR = "GET_MOVIES_POPULAR";
export const GET_MOVIES_TOPRATED = "GET_MOVIES_TOPRATED";
export const GET_MOVIE_DETAILS = "GET_MOVIE_DETAILS";
export const GET_MOVIE_BY_NAME = "GET_MOVIE_BY_NAME";
export const REMOVE_MOVIES = "REMOVE_MOVIES";
export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const GET_REQUEST_TOKEN = "GET_REQUEST_TOKEN";
export const SESSION_LOGIN = "SESSION_LOGIN";